language: go

go:
    - 1.7
env:
     - "PATH=/home/travis/gopath/bin:$PATH"
  
before_install:
    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr

script:
    - go test -v -bench=. github.com/lovedboy/gortcp/src

after_success:
    - sh ./deploy.sh
