language: go

go:
    - 1.7

before_install::

    - go get github.com/mitchellh/gox
    - go get github.com/tcnksm/ghr

script:
    - go test -v -bench=. github.com/lovedboy/gortcp/src

deploy:

  skip_cleanup: true
  provider: script
  script: sh ./deploy.sh
  on:
    branch: master
    tags: true
