language: go

go:
    - 1.7

script:
    - go test -v -bench=. github.com/lovedboy/gortcp/src

deploy:

  skip_cleanup: true
  provider: script
  script: sh ./deploy.sh
  on:
    branch: master
    tags: true
